name: Continuous Deployment

on:
  push:
    branches:
      - main
      
jobs:
  deployment_cluster:
    runs-on: ubuntu-latest

    steps:  # <-- This needs to be inside the job
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
