name: Continuous Deployment

on:
  push:
    branches:
      - main
      
jobs:
  deployment_cluster:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2  

      - name: Initialize Terraform
        run: terraform init
        working-directory: Terraform_Architecture

      - name: Validate Terraform
        run: terraform validate
        working-directory: Terraform_Architecture


      - name: apply terraform
        run: terraform apply -auto-approve
        working-directory: Terraform_Architecture

      - name: update kube config file
        run: aws eks update-kubeconfig --region ap-south-1 --name basecluster

      - name: list nodes
        run: kubectl get nodes

      - name: applying deployement
        run: | 
          kubectl apply -f k8s/
          kubectl get svc
      - name: destroy infra
        run: terraform destroy -auto-approve
        working-directory: Terraform_Architecture



      
  
